// <auto-generated />
using System;
using ECommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DataAccess.Data.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 3, 18, 55, 45, 625, DateTimeKind.Utc).AddTicks(8284),
                            Email = "doraemon@doraemon.com",
                            Name = "Doraemon",
                            Password = "$2a$10$OJ4AKll05OWIL2gMODgBp.zS38Ub8alGF50CSN9AGJxE/lSSD03zO",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 3, 18, 55, 45, 693, DateTimeKind.Utc).AddTicks(7676),
                            Email = "nobita@doraemon.com",
                            Name = "Nobita",
                            Password = "$2a$10$Uqing7CoQ9zUrAZH1Z/ce.tssHOKaMokIcuL55sOHz6L/AgL4ZPi6",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 3, 18, 55, 45, 748, DateTimeKind.Utc).AddTicks(9062),
                            Email = "shizuka@doraemon.com",
                            Name = "Shizuka",
                            Password = "$2a$10$Ul/xdmQTXWl2da1A22bmRuP5DD0UE6qqgu8v0oeNY.CDE2rbrfSSa",
                            Role = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 3, 18, 55, 45, 804, DateTimeKind.Utc).AddTicks(3544),
                            Email = "naruto@naruto.com",
                            Name = "Naruto",
                            Password = "$2a$10$1/70ojPOPGD8vAtEFKwEG.T9E3jbkFCpzJHjX0Pla48OyP.Sh3xZO",
                            Role = 1,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
