<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.BusinessLogic\ECommerce.BusinessLogic.csproj" />
    <ProjectReference Include="..\ECommerce.Core\ECommerce.Core.csproj" />
    <ProjectReference Include="..\ECommerce.DataAccess\ECommerce.DataAccess.csproj" />
  </ItemGroup>

</Project>
